WIP: Change number of parents in iota message
iotaledger/iota.go pull request #228
Opened 2020-12-20 14:54 UTC by muXxer

# Description of change

Still a draft, because checks for min and max amount are missing. Maybe we should also sort the parents?

This PR increases the number of parents of an IOTA message.

The number was limited to two parents in former times, because tip selection was too slow and without the whiteflag approach, there was an attack vector that could render large parts of the tangle invalid. Since these problems are now gone, increasing the number of parents should increase the confirmation rate, mitigate blowball attacks and decrease the confirmation time.

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Tests have been modified.

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests using ginkgo that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-01-26 15:14 UTC, luca-moser requested changes
The changes making the `MessageIDs` a slice of pointers to array pollutes the codebase with changes which otherwise wouldn't be necessary. Please revert `MessageIDs` back to be a slice of arrays. In any place where you need a slice or want to avoid copying the entire array, use `array[:]`.

2021-01-26 15:14 UTC, luca-moser commented on serializer.go
> +	}
This piece of code is duplicated at `Write64BytesArraySlice()`. Please make a separate function which given the validation mode inits the ElementValidationFunc appropriately. In fact, the switch statement should be within a method of `ArrayRules`.

2021-01-26 15:14 UTC, luca-moser commented on serializer.go
> +		// check array element validation against previous element
This comment is scattered in tests and here but it isn't always applicable. Maybe just remove it as it isn't correct.
For example, if only uniqueness is validated, the validator validates not just against the previous element. You know what I mean.

2021-01-26 15:14 UTC, luca-moser commented on serializer.go
> +func (d *Deserializer) ReadSliceOfArraysOf32Bytes(f ReadSliceOfArraysOf32BytesConsumerFunc, deSeriMode DeSerializationMode, lenType SeriSliceLengthType, arrayRules *ArrayRules, errProducer ErrProduce
Same here, change this back to not take a consumer function.

2021-01-26 15:14 UTC, luca-moser commented on serializer.go
> +
Again, refactor this toa a method of `ArrayRules`.

2021-01-26 22:35 UTC, muXxer commented
I changed everything according your comments.
I added another function `RemoveDupsAndSortByLexicalOrderArrayOf32Bytes`.
Not sure if you like the name, because I don't :D
And I don't know where to put that function :shrug: 
Hope it fits.

2021-01-27 08:47 UTC, luca-moser approved these changes
Thanks for updating the PR, looks good now!

2021-01-27 08:47 UTC, merged