Lower and Upper LivenessThreshold
iotaledger/iota.go pull request #492
Opened 2023-08-31 04:59 UTC by jonastheis

This PR introduces a lower and upper liveness threshold and makes liveness threshold a time.Duration instead of a SlotIndex.

2023-09-08 06:45 UTC, jkrvivian requested changes

2023-09-08 06:45 UTC, jkrvivian commented on api_protocol_parameters.go
> +	// LivenessThresholdLowerBound is used by tip-selection to determine the if a block is eligible by evaluating issuingTimes
```suggestion
	// LivenessThresholdLowerBound is used by tip-selection to determine if a block is eligible by evaluating issuingTimes.
```

2023-09-08 06:45 UTC, jkrvivian commented on api_protocol_parameters.go
> +	// LivenessThresholdUpperBound is used by tip-selection to determine the if a block is eligible by evaluating issuingTimes
```suggestion
	// LivenessThresholdUpperBound is used by tip-selection to determine if a block is eligible by evaluating issuingTimes
```

2023-09-28 07:50 UTC, jkrvivian approved these changes

2023-09-28 07:52 UTC, alexsporn commented on api_protocol_parameters.go
> +	LivenessThresholdUpperBound time.Duration `serix:"14,mapKey=livenessThresholdUpperBound"`
by using `time.Duration` the value in the protocol parameters is nanoseconds, so 15 seconds would be 15,000,000,000

2023-09-28 09:29 UTC, alexsporn approved these changes

2023-09-28 09:29 UTC, merged