Align naming: structure to parameters
iotaledger/iota.go pull request #559
Opened 2023-10-05 12:48 UTC by jkrvivian

* manaStructure -> manaParameters
* workScoreStructure -> workScoreParameters

2023-10-05 14:06 UTC, muXxer requested changes

2023-10-05 14:06 UTC, muXxer commented on api.go
> +	// WorkScoreParameters defines the work score structure used by the given network.
please change the comment as well.

2023-10-05 14:06 UTC, muXxer commented on api_protocol_parameters.go
> +	// WorkScoreParameters defines the work score structure used by given node/network.
please change the comment as well.

2023-10-05 14:13 UTC, muXxer approved these changes

2023-10-06 11:16 UTC, alexsporn commented
Some of the objects (Blocks and Transactions) have now an API inside and could use that one to calculate the WorkScore.
Also the TransactionBuilder does not require having it as a parameter because it contains a valid API inside.

We can do these changes in a separate PR if you don't want to do them here.

2023-10-06 12:40 UTC, cyberphysic4l commented
A further change we could make here is to do something similar to what we do with the StorageScoreParameter/StorageScoreStructure. The Parameters are what we set, and the Structure contains the Parameters plus some other values derived from the parameters, and this lives in the API. MaxBlockWorkScore, which is derived from the WorkScoreParameters would live inside this WorkScoreStructure instead of being on its own in the API in this case.

This way of doing things requires a little bit of bloating of the API but a nicer way to organise imo.

2023-10-10 15:59 UTC, closed without merging